site_name: PredaFL - Generic attack framework for federated learning

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions: 
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            group_by_category: true
            show_source: false
            separate_signature: true

nav:
  - PredaFL Docs: index.md
  - Reference:
    - reference/index.md
    - Federated learning attack framework: 
      - reference/framework/index.md
      - Utils:
        - reference/framework/utils/index.md
        - Task: reference/framework/utils/task.md
        - Data: reference/framework/utils/data.md
      - Client app: reference/framework/client.md
      - Server app: reference/framework/server.md
    - Launchers:
      - reference/launchers/index.md
      - Docker: reference/launchers/docker.md